version: '3'
services:
  api:
    build: ./api
    ports:
      - "5000:5000" # Default for flask
    expose:
      - "80"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=basf
      - NEO4J_BOLT_PORT=7687
      - NEO4J_HTTP_PORT=7474
      - NEO4J_DB_NAME=basf
    depends_on:
      - neo4j
  neo4j:
    build: ./neo4j
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # BOLT
    volumes:
      - ./data:/data
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_directories_data=/data
      - NEO4J_AUTH=neo4j/basf
